### ISSUE TITLE
CodeMirror 6 Language Support for Solidity

### ISSUE THREAD

**Issue by sergeichestakov** [alincode/codemirror-solidity#3]
Hey @alincode,

Just wanted to reach out and see if you had any plans to add [CodeMirror 6](https://codemirror.net/6/) support for this package.

This is something we're hoping to implement at @replit as we're switching to CodeMirror 6 as the primary code editor in our app very soon and hope to have Solidity support before we launch as it's a popular use case on our platform (https://blog.replit.com/solidity). 

Full language support would be ideal but even just syntax highlighting would be great. If you do decide to work on this, we'd love to help in any way we can. Let me know!

Cheers,
Sergei

**Comment by alincode** [comment]
Hi @sergeichestakov 
I got a some funding to did this project a few year ago, but fund run out of budget.
if I possible to get another funding, I might be interesting to add more feature for it.

But I just onboard in new company, kind of busy. so it's not possible do it this year.

feel free to fork it, if you need.

**Comment by sergeichestakov** [comment]
Gotcha, sounds good. We'll probably just fork and give it a go ourselves first. Thanks!
